### ISSUE TITLE
Notification Doesn't hide automatically

### ISSUE THREAD

**Issue by Senya247** [EliverLara/Sweet#131]
Whenever any kind of notification pops up, it just stays there, and doesn't go away. When i change my shell theme back to normal, it works fine. I placed the theme folder in /usr/share/themes
Any idea as to why this is happening?
(I'm using sweet Ambar theme)

**Comment by EliverLara** [comment]
Hi, could you provide more info about your OS please?

**Comment by Nightmare247** [comment]
@EliverLara sure, i have ubuntu 20.10, gnome version 3.38.1

**Comment by angela-d** [comment]
Do these both persist, too?

```
notify-send "This message will go away on it's own"
```

```
notify-send -u critical "This one will stick around until you clear it"
```

If you put the theme in `~/.local/share/themes` instead of `/usr/share/themes` does the behavior go away?

Curious as I'm also using sweet, but on Gnome 3.38.3 on Debian and I only have the `critical` types of notifications that stick around, which is expected behavior for those.

**Comment by Nightmare247** [comment]
The notification i got from the first line of code hid on it's own in about 5 seconds, while the second one stayed
i put the theme in `~/.local/share/themes`, but that didn't seem to change anything. Any notification stays there until i hover my mouse over it, then it hides.

**Comment by angela-d** [comment]
If the first one disappeared after a bit, the theme isn't necessarily impacting the notifications, otherwise that one would have stuck around as well.

What notifications do you usually see that hang around until you intervene?  Can you post a screenshot?
Perhaps the application in question is using the `critical` flag, which, by design, is meant to stick around until you acknowledge it away.

Do you use any Gnome extensions for notifications or OSD?  Always a possibility those can target certain CSS classes and have unintentional side-effects between themes.
