### ISSUE TITLE
Sidebar icon glitching

### ISSUE THREAD

**Issue by Virepri** [EliverLara/Sweet#21]
![Side bar icon glitching](https://i.imgur.com/7VHmeO5.png)

I don't quite have the words at tongue to describe this, but when the nautilus window is not focused, the wrong background color leaks in. This probably isn't intended functionality.

**Comment by badunit** [comment]
I can confirm the issue
Seems a bug in .css code, but i can't figure out on my own (and don't know if theme read gtk.css or gtk-dark.css, and i try to change some values to figure out on .css file, in Sidepanel section, but no luck so far)
Anyway, i have made a screenshot, then edited with gimp (blur part is for privacy), and when i look closely, i found all icons in sidebar panel suffer from this issue, but active element is more visible, inactive elements are less visibile.

![1](https://user-images.githubusercontent.com/44651201/50543920-f954a080-0be5-11e9-8fe8-90799e5f6a00.png)

Look closely...
![2](https://user-images.githubusercontent.com/44651201/50543921-02457200-0be6-11e9-811a-a6d1c171bf1e.png)

Anyway here is my specs:
OS: Manjaro (Kernel 4.19.12-2-Manjaro)
DE: Gnome 3.30.2
Graphics Driver:
lib32-nvidia-utils linux-419-nvidia opencl-nvidia cuda
GTK+ Theme: Sweet-Dark

(I've switch normal Sweet theme, no-dark-version, and the issue is still be there!)

**Comment by Virepri** [comment]
Next time I'm on my Arch install, I absolutely will.

**Comment by badunit** [comment]
With sidebar-issue branch, seems sidebar is ok now, but i've noticed a little animation glitch when switches places. i have troubleshoot the animation with GTK Inspector, and finally i have reach a nice result, the issue is still be here, but is imperceptible.

here is my small modification:

**gtk.css**
```css
placessidebar.sidebar row.sidebar-row .sidebar-icon:first-child {
	transition: all 200ms ease;
}

placessidebar.sidebar row.sidebar-row {
	transition: all 200ms ease;
}
```

**Comment by badunit** [comment]
I confirm with sidebar-issue branch the glitch is fixed, but there is still a problem when switching places, i have worked a solution but atm is not perfect, anyways there is an animation issue between two class who cause this issue, i have slowdown animations with GTK Inspector, but for now i don t have solved this issue.

**Comment by EliverLara** [comment]
Fixed
