### ISSUE TITLE
Theme Doesn't Apply To Status Bar and Some Panels

### ISSUE THREAD

**Issue by AhmetFarukDemir** [EliverLara/Sweet#235]
Theme doesn't apply to status bar or some panels. Theme works on apps just as expected. Is this normal? I'm using sweetdark theme
![Screenshot from 2023-05-08 12-31-09](https://user-images.githubusercontent.com/105853348/236789502-53ac3acd-a301-441b-a517-9f08dafe57f0.png)
![Screenshot from 2023-05-08 12-30-42](https://user-images.githubusercontent.com/105853348/236789507-12d0fc69-aee9-4d23-977d-27e652263cab.png)
![Screenshot from 2023-05-08 12-30-35](https://user-images.githubusercontent.com/105853348/236789510-c56d6cc2-b260-4f12-8961-6697e48a1c30.png)
![Screenshot from 2023-05-08 12-30-26](https://user-images.githubusercontent.com/105853348/236789519-2c96bd92-f6f6-43a1-a4de-1c5c1b959ab1.png)

**Comment by Coder2195Text** [comment]
https://extensions.gnome.org/extension/19/user-themes/

**Comment by EliverLara** [comment]
HI @AhmetFarukDemir  It seems your not even using the gnome-shell theme, please make sure you set the correct theme by using  the [user themes extension](https://extensions.gnome.org/extension/19/user-themes/) and download the latest version released on [gnome-look](https://www.gnome-look.org/p/1253385/)

**Comment by D3vil0p3r** [comment]
> HI @AhmetFarukDemir It seems your not even using the gnome-shell theme, please make sure you set the correct theme by using the [user themes extension](https://extensions.gnome.org/extension/19/user-themes/) and download the latest version released on [gnome-look](https://www.gnome-look.org/p/1253385/)

I downloaded Sweet-Dark-v40.tar.xz latest version from gnome-look but I have graphic flickering on Sweet Dark theme after the upgrade to GNOME 44 when I open windows or terminals (like kitty):
![image](https://github.com/EliverLara/Sweet/assets/83867734/d717726c-3f8a-43c7-a0ce-4a316e03395e)

**Comment by EliverLara** [comment]
@Coder2195Text  for libadwaita compatibility please try using [this script](https://github.com/odziom91/libadwaita-theme-changer), also as an advice in order to the theme affect apps that requires `sudo` permission you must install the your themes under `/usr/share/hemes`

**Comment by EliverLara** [comment]
@D3vil0p3r Could you provide more info about your OS please?

**Comment by D3vil0p3r** [comment]
> @D3vil0p3r Could you provide more info about your OS please?

Sure. My OS is a Arch-based OS called **Athena OS**:

Linux zen kernel: 6.3.1-zen1-1-zen
GNOME Shell version: 44.1
Display Manager: GDM

I'm running it on a Virtual Machine with 3D Acceleration enabled.

The issue occurs both on Xorg and Wayland. I reproduced the issue by opening `kitty` terminal window.

I'm also noting that, on GDM (Login Manager), if I click on top-right power button, Sweet theme is not applied, but I dont know if it is wanted:
![image](https://github.com/EliverLara/Sweet/assets/83867734/861a2c76-13fd-40e6-a921-57fd5291aa85)

**Comment by EliverLara** [comment]
@D3vil0p3r Have you noticed if the issue only occurs with the sweet theme or it's also happening with other themes?

**Comment by D3vil0p3r** [comment]
> @D3vil0p3r Have you noticed if the issue only occurs with the sweet theme or it's also happening with other themes? The GDM theming is normal because this theme does not privide a theme for Gdm.

Now I tested on [Tokyo Night](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme) (that is still not updated for GNOME 44) and I get a worse behavior:
![image](https://github.com/EliverLara/Sweet/assets/83867734/5f6bb399-fce7-447e-bb8c-f68964e21b25)

Then I tested with a theme that has been upgraded for GNOME 44, [Graphite](https://github.com/vinceliuice/Graphite-gtk-theme) and it works correctly:
![image](https://github.com/EliverLara/Sweet/assets/83867734/afd47da6-a770-431e-87b3-999dc3179bcc)

**Comment by AhmetFarukDemir** [comment]
> HI @AhmetFarukDemir It seems your not even using the gnome-shell theme, please make sure you set the correct theme by using the [user themes extension](https://extensions.gnome.org/extension/19/user-themes/) and download the latest version released on [gnome-look](https://www.gnome-look.org/p/1253385/)

Thank You! It worked. Everything seems fine.

**Comment by EliverLara** [comment]
@D3vil0p3r sorry I haven't had so much time to reproduce the issue in a similar enviroment like yours , but could it be an approach to find the root problem?  I think it could be kind of related https://github.com/EliverLara/Ant/issues/42

**Comment by D3vil0p3r** [comment]
> @D3vil0p3r sorry I haven't had so much time to reproduce the issue in a similar enviroment like yours , but could it be an approach to find the root problem? I think it could be kind of related [EliverLara/Ant#42](https://github.com/EliverLara/Ant/issues/42)

@EliverLara Uhm I'm not sure it could be related to that. About the reproducing don't worry, I give you all the details to reproduce it in a quick manner in a simple environment (Arch Linux original ISO). Here the steps:

1. Download vanilla [Arch Linux latest official ISO](https://geo.mirror.pkgbuild.com/iso/2023.05.03/archlinux-2023.05.03-x86_64.iso)
2. Create a Virtual Machine, i.e., by VMware, and mount the Arch Linux ISO mentioned above
3. Run `archinstall` command for running Arch Linux installation. Among the selections, select GNOME as Desktop Environment. I also selected linux-zen as kernel but I think it is irrilevant
4. After the installation of Arch Linux, login on the installed system, download [Sweet-Dark-v40.tar.xz from Gnome Look](https://www.gnome-look.org/p/1253385/) and extract it by `unxz Sweet-Dark-v40.tar.xz` and then `tar -xvf Sweet-Dark-v40.tar`.
5. Install kitty terminal for testing Sweet theme, by `sudo pacman -Syy kitty`
6. Copy Sweet Dark theme to the theme folder by `sudo cp -rf $HOME/Downloads/Sweet-Dark-v40 /usr/share/themes/`
7. Go to "Show Apps"
    ![image](https://github.com/EliverLara/Sweet/assets/83867734/0ae1b002-ce3d-41e6-b4af-81d2de0dbfd9)
9. Search for **Tweaks** --> Appearance --> Legacy Applications --> set "Sweet-Dark-v40"
10. Log out or reboot the machine
11. When you reach the Login Screen and click on your username, it is **VERY IMPORTANT** that you click on the gear icon on bottom-right part of the screen and select `GNOME for Xorg`. Click there, and then insert your password for login, in order to work in the Xorg environment.
12. Go to "Show Apps", search the Kitty icon and click on that:
      ![image](https://github.com/EliverLara/Sweet/assets/83867734/747437c6-5e30-4886-847e-48d31d74c041)
13. You will get the weird behaviour:
      ![image](https://github.com/EliverLara/Sweet/assets/83867734/adad121d-233d-44f7-b53f-d26b813578e8)

This bug occurs only on Xorg, but not on Wayland, and I noted that occurs at least for all Python GTK application windows.

**Comment by EliverLara** [comment]
@D3vil0p3r Could you test if replacing the `Sweet/gtk-4.0/gtk.css` file with [this one](https://github.com/EliverLara/Sweet/files/11540095/gtk.zip) fixes the issue. please?

**Comment by D3vil0p3r** [comment]
> @D3vil0p3r Could you test if replacing the `Sweet/gtk-4.0/gtk.css` file with [this one](https://github.com/EliverLara/Sweet/files/11540095/gtk.zip) fixes the issue. please?

I replaced `/usr/share/themes/Sweet-Dark-v40/gtk-4.0/gtk.css` with that new file, then I executed `ln -sf /usr/share/themes/Sweet-Dark-v40/gtk-4.0/gtk.css ./.config/gtk-4.0/gtk.css` and then I reboot, and now the issue has been fixed, so that new `gtk.css` file you provided me fixed the issue.

Will it be added on `Sweet-Dark-v40.zip` file on GNOME Look website, right?
When a new [release](https://github.com/EliverLara/Sweet/releases) will be created on GitHub repo with all these updates?

Thank you @EliverLara

**Comment by EliverLara** [comment]
> Will it be added on `Sweet-Dark-v40.zip` file on GNOME Look website, right?
> When a new [release](https://github.com/EliverLara/Sweet/releases) will be created on GitHub repo with all these updates?

Yes. I'll adopt it as the official solution and release it on gnome-look and here in github, it's kind of funny since the issue was just a value in the window shadow :sweat_smile: by the way your profile's readme looks so cool.
