### ISSUE TITLE
SDDM Theme missing dependencies in plasma6

### ISSUE THREAD

**Issue by QuantenToast** [EliverLara/Sweet#252]
I upgraded to plasma6 beta 1 (Listed as 5.90.0 in pacman) yesterday and was greeted with a broken SDDM Theme:
![PXL_20231130_123808048~2](https://github.com/EliverLara/Sweet/assets/83139587/f85058e7-fc9e-48ea-9d46-7f4f41a96538)

If I haven't missed something it seems like the required QtQuick.Controls version doesn't ship with the latest plasma.

I'm using the AUR sweet-kde-git version.

Thanks in advance for every bit of Information!

**Comment by pkprotoplasm** [comment]
The KDE themes will need to be updated for Qt6 and Plasma 6. In the case of your error message, the QtQuick controls version for the new Plasma environment will be 2.0 instead of 1.1.

It doesn't appear to be a matter of trivial updates to the QML includes, though. After bumping the includes for Plasma and Qt6 QML compatibility, I've found there are other issues with breaking API changes that would need to be resolved for the themes to apply correctly. Sadly I don't have the knowledge to contribute those changes.

**Comment by QuantenToast** [comment]
I'm closing this issue in favor of  #259
