### ISSUE TITLE
Changing the GDM Theme

### ISSUE THREAD

**Issue by xmegapixelx** [EliverLara/Sweet#46]
Hi. Is there any way to change the GDM theme (login screen)? I am on Pop_os and the standard theme does not match the shell theme. Thanks.

**Comment by EliverLara** [comment]
So far there is not a GDM theme included, sorry.

**Comment by khlr** [comment]
Since this is a very old question and there isn't a GDM theme yet, I think you have no plans to create one, do you, @EliverLara ?

That's kinda sad, because I really love your sweet themes (and the others are great as well!). Having a styled login screen would be really nice!
I really, really appreciate your hard work!
